<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Datetime\Module'                        => __DIR__ . '/Module.php',
    'Datetime\Controller\IndexController' => __DIR__ . '/src/Datetime/Controller/IndexController.php',
    'DatetimeTest\Framework\TestCase'        => __DIR__ . '/tests/Datetime/Framework/TestCase.php',
    'DatetimeTest\SampleTest'                => __DIR__ . '/tests/Datetime/SampleTest.php',
);
